oopd-project/Models/Classes.cs
namespace oopd_project.Models;

public class Classes
{
    public List<Class> AvailableClasses { get; set; }
    public Class ClassToAdd { get; set; }
}

oopd-project/Models/Subscription.cs
using System;
namespace oopd_project.Models
{
	public class Subscription
	{
		public SubscriptionType SubscriptionType { get; set; }
		public DateTime StartingDate { get; set; }
		public int Duration { get; set; }
		public DateTime EndingDate { get; set; }
		public bool IsAvailabel { get; set; }
		public bool IsActive { get; set; }
	}
}

oopd-project/Models/SubscriptionType.cs
namespace oopd_project.Models;

public class SubscriptionType
{
    public int Subscription_Type_ID { get; set; }
    public string Subscription_Type_Name { get; set; }
    public decimal Price { get; set; }
    public double Duration { get; set; }
    public bool IsAvailable { get; set; }
    
    public List<Class> Classes { get; set; }
    public List<int> ClassesInSubscription { get; set; }
}

oopd-project/Models/Subscriptions.cs
namespace oopd_project.Models;

public class Subscriptions
{
    public List<SubscriptionType> SubscriptionTypes { get; set; }
    public SubscriptionType SubscriptionTypeToAdd { get; set; }
    public List<Class> AvailableClasses { get; set; }
    
    public Subscription CurrentSubscription { get; set; }
}

oopd-project/Controllers/AdministratorMainPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Transactions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using oopd_project.DBContext.DBModels;
using oopd_project.Models;
using Class = oopd_project.Models.Class;
using Schedule = oopd_project.Models.Schedule;

namespace oopd_project.Controllers
{
    public class AdministratorMainPageController : Controller
    {
        public IActionResult Index()
        {
            ClearUnavailableScheduleItems();
            var schedule = GetCurrentClubSchedule();
            schedule._AvailableClasses = GetAvailableClassesForSchedule();
            return View("Index", schedule);
        }
        
        public IActionResult Classes()
        {
            var availableClasses = GetAvailableClasses();
            var classes = new Classes();
            classes.AvailableClasses = availableClasses;
            return View("Classes", classes);
        }

        public IActionResult Subscriptions()
        {
            var availableSubscriptionTypes = GetSubscriptionTypes();
            var availableClasses = GetAvailableClasses();
            var subscriptions = new Subscriptions
            {
                SubscriptionTypes = availableSubscriptionTypes,
                AvailableClasses = availableClasses
            };
           
            return View("Subscriptions", subscriptions);
        }

        public IActionResult CreateSubscription(Subscriptions subscriptions, int[] SelectedClasses)
        {
            subscriptions.SubscriptionTypeToAdd.ClassesInSubscription = SelectedClasses.ToList();

            AddNewSubscriptionType(subscriptions);
            
            return Subscriptions();
        }

        public IActionResult AddClass(Classes classes)
        {
            using DataBaseContext db = new DataBaseContext();
            DBContext.DBModels.Class classToAdd = new DBContext.DBModels.Class
            {
                Class_Name = classes.ClassToAdd.Name,
                Description = classes.ClassToAdd.Description,
                Duration = classes.ClassToAdd.Duration.TotalHours,
                Max_Participants = classes.ClassToAdd.MaxNumberOfPeople
            };
            db.Classes.Add(classToAdd);
            db.SaveChanges();
            return Classes();
        }
        
        public IActionResult DeclineClass(int scheduleItemId)
        {
            DeclineScheduleItemFromDB(scheduleItemId);
            return Index();
        }

        public IActionResult AddToSchedule(Schedule updatedSchedule)
        {
            if (updatedSchedule._ClassToAdd != null)
            {
                using (DataBaseContext db = new DataBaseContext())
                {
                    var date = updatedSchedule._ClassToAdd.SelectedDate;
                    var time = updatedSchedule._ClassToAdd.SelectedTime;

                    var scheduleItem = new DBContext.DBModels.Schedule
                    {
                        Class_ID = updatedSchedule._ClassToAdd.ClassId,
                        Date_Time = date.Add(time),
                        IsAvailable = true
                    };

                    db.Schedule.Add(scheduleItem);
                    db.SaveChanges();
                }
            }
            var schedule = GetCurrentClubSchedule();
            schedule._AvailableClasses = GetAvailableClassesForSchedule();
            return Index();
        }

        public IActionResult DeleteClass(int classId)
        {
            DeleteClassFromDB(classId);
            
            return Classes();
        }

        public IActionResult DeleteSubscription(int subscriptionTypeId)
        {
            DeleteSubscriptionFromDB(subscriptionTypeId);
            return Subscriptions();
        }

        private List<Class> GetAvailableClassesForSchedule()
        {
            List<Class> availableClasses = new List<Class>();

            using (var scope = new TransactionScope())
            {
                try
                {
                    using (DataBaseContext db = new DataBaseContext())
                    {
                        // Your existing logic to fetch classes from the database
                        var currentClassesList = db.Classes.ToList();
                        foreach (var item in currentClassesList)
                        {
                            if (item.Coach_ID != null)
                            {
                                var availableClass = new Class
                                {
                                    Id = item.Class_ID,
                                    Name = item.Class_Name,
                                    MaxNumberOfPeople = item.Max_Participants,
                                    Description = item.Description,
                                    Duration = TimeSpan.FromHours(item.Duration),
                                };
                                availableClasses.Add(availableClass);
                            }
                        }
                        scope.Complete();
                    }
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            }

            return availableClasses;
        }
        
        private List<Class> GetAvailableClasses()
        {
            List<Class> availableClasses = new List<Class>();

            using (var scope = new TransactionScope())
            {
                try
                {
                    using (DataBaseContext db = new DataBaseContext())
                    {
                        var currentClassesList = db.Classes.ToList();
                        foreach (var item in currentClassesList)
                        {
                            var availableClass = new Class
                            {
                                Id = item.Class_ID,
                                Name = item.Class_Name,
                                MaxNumberOfPeople = item.Max_Participants,
                                Description = item.Description,
                                Duration = TimeSpan.FromHours(item.Duration),
                            };
                            availableClasses.Add(availableClass);
                        }
                        
                        scope.Complete();
                    }
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            }

            return availableClasses;
        }
        
        private void DeclineScheduleItemFromDB(int id)
        {
            using (var scope = new TransactionScope())
            {
                try
                {
                    using (DataBaseContext db = new DataBaseContext())
                    {
                        var existingClass = db.Schedule.Find(id);
                        if (existingClass != null)
                        {
                            existingClass.IsAvailable = false;
                            db.SaveChanges();
                        }
                        
                        scope.Complete();
                    }
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            }
        }
        
        private Schedule GetCurrentClubSchedule()
        {
            Schedule schedule = new Schedule
            {
                _Schedule = new List<ScheduleItem>()
            };

            using (var scope = new TransactionScope())
            {
                try
                {
                    using (DataBaseContext db = new DataBaseContext())
                    {
                        var currentScheduleList = db.Schedule
                            .Include(s => s.Class).ThenInclude(@class => @class.Coach)
                            .Where(s => s.IsAvailable == true)
                            .OrderBy(s => s.Date_Time)
                            .ToList();

                        foreach (var item in currentScheduleList)
                        {
                            var scheduleItem = new ScheduleItem()
                            {
                                Class = new Class()
                                {
                                    Name = item.Class.Class_Name,
                                    Duration = TimeSpan.FromHours(item.Class.Duration),
                                    Description = item.Class.Description,
                                    MaxNumberOfPeople = item.Class.Max_Participants
                                },
                                ScheduleItemId = item.Schedule_Item_ID,
                                DateTime = item.Date_Time
                            };

                            schedule._Schedule.Add(scheduleItem);
                        }
                        
                        scope.Complete();
                    }
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            }

            return schedule;
        }
        
        private List<SubscriptionType> GetSubscriptionTypes()
        {
            List<SubscriptionType> subscriptionTypes = new List<SubscriptionType>();

            using (var scope = new TransactionScope())
            {
                try
                {
                    using (DataBaseContext db = new DataBaseContext())
                    {
                        var currentSubscriptionTypes = db.Subscription_Types.ToList();
                        foreach (var item in currentSubscriptionTypes)
                        {

oopd-project/Views/AdministratorMainPage/Classes.cshtml
@model Classes;

@{
    ViewData["Title"] = "Classes Page";
}

<h2 class="mb-4">Classes Management</h2> 

<h4>Add New Class</h4>

<form asp-controller="AdministratorMainPage" asp-action="AddClass" method="post">
    <div class="form-row">
        <div class="form-group col-md-4">
            <label asp-for="@Model.ClassToAdd.Name">Class Name:</label>
            <input asp-for="@Model.ClassToAdd.Name" class="form-control" />
        </div>
        <div class="form-group col-md-4">
            <label asp-for="@Model.ClassToAdd.Description">Description:</label>
            <input asp-for="@Model.ClassToAdd.Description" class="form-control" />
        </div>
        <div class="form-group col-md-2">
            <label asp-for="@Model.ClassToAdd.MaxNumberOfPeople">Max Number of People:</label>
            <input asp-for="@Model.ClassToAdd.MaxNumberOfPeople" class="form-control" />
        </div>
        <div class="form-group col-md-2">
            <label asp-for="@Model.ClassToAdd.Duration">Duration:</label>
            <input asp-for="@Model.ClassToAdd.Duration" type="time" class="form-control" />
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Add Class</button>
</form>

@if (Model.AvailableClasses != null && Model.AvailableClasses.Any())
{
    <div class="table-responsive mt-4">
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>Class name</th>
                    <th>Description</th>
                    <th>Max number of people</th>
                    <th>Duration</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.AvailableClasses)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.Description</td>
                        <td>@item.MaxNumberOfPeople</td>
                        <td>@item.Duration.ToString("hh':'mm")</td>
                        <td>
                            <form method="post" asp-controller="AdministratorMainPage" asp-action="DeleteClass">
                                <input type="hidden" name="classId" value="@item.Id"/>
                                <button type="submit" class="btn btn-danger">Delete Class</button>
                            </form>
                            </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="alert alert-info mt-4"> 
        <p>No available classes right now</p>
    </div>
}

oopd-project/Views/AdministratorMainPage/Index.cshtml
@model Schedule

@{
    ViewData["Title"] = "Club Schedule";
}

<h2 class="mb-4">Current Schedule</h2>

<form asp-controller="AdministratorMainPage" asp-action="AddToSchedule" method="post">
    <div class="form-row mb-3">
        <div class="col-md-4">
            <label asp-for="@Model._ClassToAdd.ClassId">Select Class:</label>
            <select asp-for="@Model._ClassToAdd.ClassId" asp-items="@(new SelectList(Model._AvailableClasses, "Id", "Name"))" class="form-control">
            </select>
        </div>
        <div class="col-md-4">
           <label asp-for="@Model._ClassToAdd.SelectedDate">Select Date:</label>
           <input asp-for="@Model._ClassToAdd.SelectedDate" type="date" class="form-control" required>
        </div>
        <div class="col-md-4">
          <label asp-for="@Model._ClassToAdd.SelectedTime">Select Time:</label>
          <input asp-for="@Model._ClassToAdd.SelectedTime" type="time" class="form-control" required>
        </div>
    </div>
    <input type="hidden" asp-for="@Model._ClassToAdd.ClassId" name="classId" />

    <button type="submit" class="btn btn-success">Add to Schedule</button>
</form>


@if (Model != null && Model._Schedule.Any())
{
    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>Class name</th>
                    <th>Max Participants</th>
                    <th>Day</th>
                    <th>Time</th>
                    <th>Duration</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model._Schedule)
                {
                    <tr>
                        <td>@item.Class.Name</td>
                        <td>@item.Class.MaxNumberOfPeople</td>
                        <td>@item.DateTime.ToString("MM/dd/yyyy")</td>
                        <td>@item.DateTime.ToString("hh:mm tt")</td>
                        <td>@item.Class.Duration.ToString("hh':'mm")</td>
                        <td>
                            <div class="btn-group btn-group-sm">
                                <a asp-controller="AdministratorMainPage" asp-action="DeclineClass" asp-route-scheduleItemId="@item.ScheduleItemId" class="btn btn-primary">Decline it</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="alert alert-info mt-4">
        <p>You have no classes in the nearest future :)</p>
    </div>
}

oopd-project/Views/AdministratorMainPage/Subscriptions.cshtml
@model Subscriptions

@{
    ViewData["Title"] = "Subscription Types";
}

<h2 class="mb-4">Create New Subscription</h2>

<form asp-controller="AdministratorMainPage" asp-action="CreateSubscription" method="post">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="@Model.SubscriptionTypeToAdd.Subscription_Type_Name">Subscription Type Name:</label>
            <input type="text" asp-for="@Model.SubscriptionTypeToAdd.Subscription_Type_Name" class="form-control" required />
        </div>
        <div class="form-group col-md-6">
            <label asp-for="@Model.SubscriptionTypeToAdd.Price">Price:</label>
            <input type="number" asp-for="@Model.SubscriptionTypeToAdd.Price" class="form-control" required />
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-12">
            <label>Available Classes:</label>
            <div>
                @foreach (var classItem in Model.AvailableClasses)
                {
                    <div class="form-check form-check-inline">
                        <input type="checkbox" name="SelectedClasses" value="@classItem.Id" class="form-check-input class-checkbox" />
                        <label class="form-check-label">@classItem.Name</label>
                    </div>
                }
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Add</button>
</form>


<hr />

<h2 class="mt-4">Existing Subscriptions</h2>

<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Available</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var subscriptionType in Model.SubscriptionTypes)
        {
            <tr>
                <td>@subscriptionType.Subscription_Type_Name</td>
                <td>@subscriptionType.Price</td>
                <td>@(subscriptionType.IsAvailable ? "Yes" : "No")</td>
                <td>
                    <form method="post" asp-controller="AdministratorMainPage" asp-action="DeleteSubscription">
                        <input type="hidden" name="subscriptionTypeId" value="@subscriptionType.Subscription_Type_ID"/>
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                    </td>
            </tr>
        }
    </tbody>
</table>