oopd-project/Models/Classes.cs
namespace oopd_project.Models;

public class Classes
{
    public List<Class> AvailableClasses { get; set; }
    public Class ClassToAdd { get; set; }
}

oopd-project/Controllers/CoachMainPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Transactions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using oopd_project.Models;

namespace oopd_project.Controllers
{
    public class CoachMainPageController : Controller
    {
        private static int? _coachId;

        public IActionResult Index()
        {
            var coachSchedule = GetCoachSchedule();
            return View("Index", coachSchedule);
        }

        public IActionResult Classes()
        {
            var availableClasses = GetAvailableClasses();
            return View("Classes", availableClasses);
        }
        
        public IActionResult TakeClass(int id)
        {
            AssureClassFromDB(id);
            var availableClasses = GetAvailableClasses();
            return View("Classes", availableClasses);
        }

        public IActionResult DeclineClass(int id, string name, string description)
        {
            DeclineClassFromDB(id, name, description);
            var coachSchedule = GetCoachSchedule();
            return View("Index", coachSchedule);
        }
        
        private Schedule GetCoachSchedule()
        {
            Schedule coachSchedule = new Schedule
            {
                _Schedule = new List<ScheduleItem>()
            };
            _coachId = HttpContext.Session.GetInt32("UserId");

            using (var scope = new TransactionScope(TransactionScopeOption.Suppress))
            {
                try
                {
                    using (DataBaseContext db = new DataBaseContext())
                    {
                        var coachCurrentList = db.Schedule
                            .Include(s => s.Class)
                            .Where(s => s.Class.Coach_ID == _coachId && s.Date_Time > DateTime.Now && s.Date_Time < DateTime.Now.AddDays(7))
                            .ToList();

                        foreach (var item in coachCurrentList)
                        {
                            var scheduleItem = new ScheduleItem()
                            {
                                Class = new Class()
                                {
                                    Id = item.Class_ID,
                                    Name = item.Class.Class_Name,
                                    Duration = TimeSpan.FromHours(item.Class.Duration),
                                    Description = item.Class.Description,
                                    MaxNumberOfPeople = item.Class.Max_Participants
                                },
                                DateTime = item.Date_Time
                            };

                            coachSchedule._Schedule.Add(scheduleItem);
                        }
                    }
                    scope.Complete();
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            }

            return coachSchedule;
        }
        
        private List<Class> GetAvailableClasses()
        {
            List<Class> classes = new List<Class>();
            _coachId = HttpContext.Session.GetInt32("UserId");

            using (var scope = new TransactionScope(TransactionScopeOption.Suppress))
            {
                try
                {
                    using (DataBaseContext db = new DataBaseContext())
                    {
                        var availableClasses = db.Classes.Where(c => c.Coach_ID == null).ToList();

                        foreach (var item in availableClasses)
                        {
                            var _class = new Class()
                            {
                                Id = item.Class_ID,
                                Name = item.Class_Name,
                                Duration = TimeSpan.FromHours(item.Duration),
                                Description = item.Description,
                                MaxNumberOfPeople = item.Max_Participants
                            };
                            classes.Add(_class);
                        }
                    }
                    scope.Complete();

                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            }

            return classes;
        }

        private void AssureClassFromDB(int id)
        {
            using (var scope = new TransactionScope())
            {
                try
                {
                    using (DataBaseContext db = new DataBaseContext())
                    {
                        var existingClass = db.Classes.Find(id);
                        if (existingClass != null)
                        {
                            existingClass.Coach_ID = _coachId;
                            db.SaveChanges();
                        }
                        
                        scope.Complete();
                    }
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            }
        }
        
        private void DeclineClassFromDB(int id, string name, string description)
        {
            using (var scope = new TransactionScope())
            {
                try
                {
                    using (DataBaseContext db = new DataBaseContext())
                    {
                        var existingClass = db.Classes.FirstOrDefault(c => c.Class_ID == id && c.Class_Name == name && c.Description == description);
                        if (existingClass != null)
                        {
                            existingClass.Coach_ID = null;
                            db.SaveChanges();
                        }
                        
                        scope.Complete();
                    }
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            }
        }

    }
}

oopd-project/Views/CoachMainPage/Classes.cshtml
@model List<Class>;

@{
    ViewData["Title"] = "Classes Page";
}

<h2 class="mb-4">All possible classes Classes</h2> 

@if (Model != null && Model.Any())
{
    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>Class name</th>
                    <th>Description</th>
                    <th>Max number of people</th>
                    <th>Duration</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.Description</td>
                        <td>@item.MaxNumberOfPeople</td>
                        <td>@item.Duration.ToString("hh':'mm")</td>
                        <td>
                            <div class="btn-group btn-group-sm">
                                <a asp-controller="CoachMainPage" asp-action="TakeClass" asp-route-id="@item.Id" class="btn btn-primary">Take it</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="alert alert-info mt-4"> 
        <p>No unassigned classes now</p>
    </div>
}

oopd-project/Views/CoachMainPage/Index.cshtml
@model Schedule

@{
    ViewData["Title"] = "Main Page";
}

<h2 class="mb-4">Your Current Classes</h2> 

@if (Model != null && Model._Schedule.Any())
{
    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>Class name</th>
                    <th>Description</th>
                    <th>Max Participants</th>
                    <th>Day</th>
                    <th>Time</th>
                    <th>Duration</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model._Schedule)
                {
                    <tr>
                        <td>@item.Class.Name</td>
                        <td>@item.Class.Description</td>
                        <td>@item.Class.CurrentNumberOfPeople</td>
                        <td>@item.DateTime.ToString("MM/dd/yyyy")</td>
                        <td>@item.DateTime.ToString("hh:mm tt")</td>
                        <td>@item.Class.Duration.ToString("hh':'mm")</td>
                        <td>
                            <div class="btn-group btn-group-sm">
                                <a asp-controller="CoachMainPage" asp-action="DeclineClass" asp-route-id="@item.Class.Id" asp-route-name="@item.Class.Name" asp-route-description="@item.Class.Description" class="btn btn-primary">Decline it</a>
                            </div>
                            </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="alert alert-info mt-4"> 
        <p>You have no classes in the nearest future :)</p>
    </div>
}